name: CICD Pipeline for Feature Branches

on:
  push:
    branches:
      - "feature/*"
  pull_request:
    branches:
      - "feature/*"
  workflow_dispatch:

permissions:
  contents: read
  security-events: write

jobs:
  unit_test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install Dependencies
      run: npm ci
      working-directory: ./src

    - name: Run Tests
      run: npm test
      working-directory: ./src

  sonar_scan:
    runs-on: ubuntu-latest
    needs: unit_test
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v4
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  build_scan_post_image:
    runs-on: ubuntu-latest
    needs: sonar_scan
    outputs:
      time: ${{ steps.set-timestamp.outputs.time }}

    steps:
    - uses: actions/checkout@v4

    - name: Set Timestamp Variable
      id: set-timestamp
      run: echo "::set-output name=time::$(date +%s)"

    - name: Build the Docker image
      run: |
        docker build . --file Dockerfile --tag chucthien03/golden-owl:${{ steps.set-timestamp.outputs.time }}
        docker image tag chucthien03/golden-owl:${{ steps.set-timestamp.outputs.time }} chucthien03/golden-owl:latest
        docker images
      working-directory: ./src
    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@master
      with:
          image-ref: 'chucthien03/golden-owl:latest'
          format: 'sarif'
          output: 'trivy-results.sarif'
          severity: 'CRITICAL,HIGH'
    - name: Upload Trivy scan results to GitHub Security tab
      uses: github/codeql-action/upload-sarif@v3
      with:
          sarif_file: 'trivy-results.sarif'
    - name: Authenticate with Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login --username ${{ secrets.DOCKER_USERNAME }} --password-stdin
    - name: Push new image to Docker Hub
      run: |
        docker push chucthien03/golden-owl:${{ steps.set-timestamp.outputs.time }}
        docker push chucthien03/golden-owl:latest
      

  deploy_test_env:
    runs-on: self-hosted
    needs: build_scan_post_image
    steps:
    - name: Replace the old image
      run: |
        # Stop and remove the old container
        docker rm -f my-container || true
        # Remove unused images with the same name
        docker images chucthien03/golden-owl -q | xargs -r docker rmi -f
        # Run the new container
        docker run -dp 80:3000 -p 443:3000 --name my-container chucthien03/golden-owl:latest
        # Verify the container and image
        docker ps
        docker images

    - name: Verify Deployment Health
      run: |
        curl -f http://localhost || echo "Deployment failed"
