name: CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    # Bước thiết lập biến Time
    - name: Set Timestamp Variable
      id: set-timestamp
      run: echo "Time=$(date +%s)" >> $GITHUB_ENV

    - name: Build the Docker image
      run: |
        docker build . --file Dockerfile --tag chucthien03/golden-owl:${{ env.Time }}
        docker images
      working-directory: ./src

    - name: Authenticate with Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login --username ${{ secrets.DOCKER_USERNAME }} --password-stdin

    - name: Push new image to Docker Hub
      run: docker push chucthien03/golden-owl:${{ env.Time }}
