
name: Pipeline Production

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  security-events: write
jobs:
  deploy_prod_env:
      runs-on: production
      steps:
      - name: Replace the old image
        run: |
          docker rm -f my-container || true
          docker images chucthien03/golden-owl -q | xargs -r docker rmi -f
          docker run -dp 80:3000 -p 443:3000 --name my-container chucthien03/golden-owl:latest
          docker ps
          docker images

      - name: Verify Deployment Health
        run: |
          curl -f http://localhost || echo "Deployment failed"
